name: hrm_aqtech
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5
  http: ^1.2.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  flutter_localization: ^0.2.2
  flutter_slidable: ^3.1.1
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^26.2.14
  month_year_picker: ^0.4.0+1
  pie_chart: ^5.4.0
  image_picker: ^0.8.5+3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.png"
  image_path_android: "assets/logos/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/logos/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/
    - assets/logos/
    - assets/users/
    - assets/animations/
    - assets/icons/
    - assets/placeholder/
    # - assets/placeholder/avatar_placeholder.png
